name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm
        shell: bash

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run build
        run: pnpm run build
        shell: bash

      - name: Run tests
        run: pnpm run test
        shell: bash